/**
 * next-env.d.ts is regenerated by Next.js on every build and dev start, and
 * anything hand-added to it is silently discarded — that bit it, once,
 * earlier in this project. This file is not touched by that process, so the
 * declaration survives.
 */
declare module '*.css';
